
//Day1.testFirst ()
//Day1.runFirst ()
//Day1.testSecond ()
//Day1.runSecond ()
//Day2.testFirst ()
//Day2.solveFirst ()
//Day2.testSecond ()
//Day2.solveSecond ()
//Day3.testFirst ()
//Day3.solveFirst ()
Day3.testSecond ()
Day3.solveSecond ()